image: docker
services:
  - docker:dind
stages:
  - init
  - tests
  - deploy
init:
  stage: init
  script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - whoami
run_tests:
  stage: tests
  script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker-compose up tests
deploy_staging:
  stage: deploy
  script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker-compose up terraform
  environment:
    name: staging
  only:
    - master
deploy_production:
  stage: deploy
  script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker-compose up terraform
  environment:
    name: production
  when: manual
  only:
    - master