image: aukhan/postgresql

stages:
  - ver
  - init
  - tests
  - deploy

ver:
  stage: ver
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -yq update && apt-get install -y gnupg2
    - apt-get -yq install libffi6 libffi-dev
    - apt-get -yq install software-properties-common git curl
    - add-apt-repository ppa:deadsnakes/ppa -y
    - apt-get -yq update
    - apt-get -yq install wget
    - apt-get -yq install python3.6
    - apt-get -yq install python3.6-dev
    - apt-get -yq install python3.6-venv
    - wget https://bootstrap.pypa.io/get-pip.py
    - python3.6 get-pip.py
    - ln -s /usr/bin/python3.6 /usr/local/bin/python3
    - ln -s /usr/bin/python3.6 /usr/local/bin/python
    - python --version
    - whoami

variables:
  PYTHONPATH: .
  FLASK_APP: server

init:
  stage: init
  script:
    - export LC_CTYPE=en_US.UTF-8
    - export LANG=en_US.UTF-8
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -yq update && apt-get install -y gnupg2
    - apt-get -yq install libffi6 libffi-dev
    - apt-get -yq install software-properties-common git curl
    - add-apt-repository ppa:deadsnakes/ppa -y
    - apt-get -yq update
    - apt-get -yq install wget postgresql-server-dev-10
    - apt-get -yq install python3.6
    - apt-get -yq install python3.6-dev
    - apt-get -yq install python3.6-venv
    - wget https://bootstrap.pypa.io/get-pip.py
    - python3.6 get-pip.py
    - ln -s /usr/bin/python3.6 /usr/local/bin/python3
    - ln -s /usr/bin/python3.6 /usr/local/bin/python
    - pip3 install psycopg2-binary
    - pip3 install gunicorn
    - pip3 install -r requirements.txt

run_tests:
  stage: tests
  script:
    - export LC_CTYPE=en_US.UTF-8
    - export LANG=en_US.UTF-8
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -yq update && apt-get install -y gnupg2
    - apt-get -yq install libffi6 libffi-dev
    - apt-get -yq install software-properties-common git curl
    - add-apt-repository ppa:deadsnakes/ppa -y
    - apt-get -yq update
    - apt-get -yq install wget postgresql-server-dev-10
    - apt-get -yq install python3.6
    - apt-get -yq install python3.6-dev
    - apt-get -yq install python3.6-venv
    - wget https://bootstrap.pypa.io/get-pip.py
    - python3.6 get-pip.py
    - ln -s /usr/bin/python3.6 /usr/local/bin/python3
    - ln -s /usr/bin/python3.6 /usr/local/bin/python
    - pip3 install psycopg2-binary
    - pip3 install gunicorn
    - pip3 install -r requirements.txt
    - psql -c 'create database software_hr;'
    - export ENV=test
    - flask db upgrade
    - python tests.py

deploy_staging:
  stage: deploy
  script:
    - export ENV=heroku
    - flask db upgrade
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/software-hr.git
    - git push heroku master
    - echo "Deployed to Staging Server https://software-hr.herokuapp.com/"
  environment:
    name: staging
    url: https://software-hr.herokuapp.com/
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - export ENV=heroku
    - flask db upgrade
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/software-hr.git
    - git push heroku master
    - echo "Deployed to Production Server https://software-hr.herokuapp.com/"
  environment:
    name: production
    url: https://software-hr.herokuapp.com/
  when: manual
  only:
    - master