image: bopen/ubuntu-pyenv

stages:
  - ver
  - init
  - tests
  - deploy

ver:
  stage: ver
  script:
    - python --version
    - whoami

variables:
  PYTHONPATH: .
  FLASK_APP: server

init:
  stage: init
  script:
    - apt-get update && apt-get install -y gnupg2
    - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
    - echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" > /etc/apt/sources.list.d/pgdg.list
    - apt-get update && apt-get install -y software-properties-common postgresql-10 postgresql-client-10 postgresql-contrib-10 postgresql-server-dev-10
    - apt-get install libffi6 libffi-dev
    - pip3 install psycopg2-binary
    - pip3 install gunicorn
    - pip3 install -r requirements.txt

run_tests:
  stage: tests
  script:
    - apt-get update && apt-get install -y gnupg2
    - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
    - echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" > /etc/apt/sources.list.d/pgdg.list
    - apt-get update && apt-get install -y software-properties-common postgresql-10 postgresql-client-10 postgresql-contrib-10 postgresql-server-dev-10
    - apt-get install libffi6 libffi-dev
    - pip3 install psycopg2-binary
    - pip3 install gunicorn
    - pip3 install -r requirements.txt
    - export ENV=test
    - flask db upgrade
    - python tests.py

deploy_staging:
  stage: deploy
  script:
    - export ENV=heroku
    - flask db upgrade
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/software-hr.git
    - git push heroku master
    - echo "Deployed to Staging Server https://software-hr.herokuapp.com/"
  environment:
    name: staging
    url: https://software-hr.herokuapp.com/
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - export ENV=heroku
    - flask db upgrade
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/software-hr.git
    - git push heroku master
    - echo "Deployed to Production Server https://software-hr.herokuapp.com/"
  environment:
    name: production
    url: https://software-hr.herokuapp.com/
  when: manual
  only:
    - master