"""empty message

Revision ID: dae730f64719
Revises: 6d39d873e510
Create Date: 2020-02-13 12:46:04.449894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae730f64719'
down_revision = '6d39d873e510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('jid', sa.String(length=100), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('jid')
    )
    op.create_table('orig_repos',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('open_issue', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comfork', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('fork', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fork'], ['orig_repos.uid'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('tags',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('repo_tag',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['orig_repos.uid'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.uid'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('software',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Float(), nullable=True),
    sa.Column('pkgname', sa.String(length=50), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['orig_repos.uid'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('modules',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('security_issues', sa.Integer(), nullable=True),
    sa.Column('performance', sa.Integer(), nullable=True),
    sa.Column('inlining_performance', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cat', sa.String(length=50), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['software.uid'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('modules_modules',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modules1_id', sa.Integer(), nullable=False),
    sa.Column('modules2_id', sa.Integer(), nullable=False),
    sa.Column('deprate', sa.Float(), nullable=True),
    sa.Column('dep_cat', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['modules1_id'], ['modules.uid'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modules2_id'], ['modules.uid'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modules_modules')
    op.drop_table('modules')
    op.drop_table('software')
    op.drop_table('repo_tag')
    op.drop_table('tags')
    op.drop_table('orig_repos')
    op.drop_table('job')
    # ### end Alembic commands ###
